### ISSUE TITLE
Refreshing the page on any route will result in a 404 error

### ISSUE THREAD

**Issue by Soul-Code** [SixK/coco-annotator-ng#11]
Refreshing the page on any route (excluding the root route) will result in a 404 error.

![image](https://github.com/user-attachments/assets/29b64152-feba-4e79-aa2e-5f46dc77b7ce)

**Comment by SixK** [comment]
problem confirmed here.
I will investigate.

**Comment by SixK** [comment]
Was not that easy to fix or maybe I missed something obvious,  
but should be fixed with this commit 2eaa1067efd8cf3e7186c5896fb6392bddbdc166  

I also added a fix with docker-compose.gpu.yml that was not findind my GPU due to a missing option in docker-compose file.

Don't forget:
- docker-compose.dev.yml is for developpement and run with debug (it should be a bit slower) and AI tools.
- docker-compose.yml run containers in production mode without AI tools.
- docker-compose.gpu.yml run containers in production mode with AI tools (but ai container need about 20 Go disk space)
- docker-compose.build.yml is to build docker-compose.yml containers. I don't know why it's not done directly with docker-compose.yml, but it's a legacy file)

**Comment by Soul-Code** [comment]
Hi @SixK,

Thank you so much for your effort and the detailed explanation! The fix in commit https://github.com/SixK/coco-annotator-ng/commit/2eaa1067efd8cf3e7186c5896fb6392bddbdc166 worked perfectly, and everything is running smoothly now. I appreciate your help and the additional information about the docker-compose files. 😊
